<?php

return [
    'custom-logo'                         => true,
    'html5'                               => true,
    'menus'                               => true,
    'post-thumbnails'                     => true,
    'admin-bar'                           => false,
    'align-wide'                          => false,
    'automatic-feed-links'                => false,
    'core-block-patterns'                 => false,
    'custom-background'                   => false,
    'custom-header'                       => false,
    'custom-line-height'                  => false,
    'customize-selective-refresh-widgets' => false,
    'custom-spacing'                      => false,
    'custom-units'                        => false,
    'dark-editor-style'                   => false,
    'disable-custom-colors'               => false,
    'disable-custom-font-sizes'           => false,
    'editor-color-palette'                => false,
    'editor-gradient-presets'             => false,
    'editor-font-sizes'                   => false,
    'editor-styles'                       => false,
    'featured-content'                    => false,
    'post-formats'                        => false,
    'responsive-embeds'                   => false,
    'starter-content'                     => false,
    'title-tag'                           => false,
    'wp-block-styles'                     => false,
    'widgets'                             => false,
    'widgets-block-editor'                => false,
];
